server:
  port: ${SERVER_PORT:8881}

spring:
  main:
    banner-mode: off
  datasource:
    url: jdbc:postgresql://${IP_DATABASE:localhost}:${DATABASE_PORT:5432}/${DATABASE_NAME:product}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}

  graphql:
    graphiql:
      enabled: true
      path: /graphiql

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true